name: Nightly Push

on:
  # schedule:
    # every 15 minutes
    # - cron:  '*/15 * * * *'
  workflow_dispatch:

jobs:
  deploy-nightly:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    # config GIT globally so it can do git push
    - uses: fregante/setup-git-user@v1
    - name: Use Node.js 12.x
      uses: actions/setup-node@v1
      with:
        node-version: 12.x
    - run: npm i -g yarn
    - run: yarn install --frozen-lockfile
    - run: yarn deploy-nightly
