name: Nightly Push

on:
  schedule:
    # every 15 minutes
    - cron:  '*/15 * * * *'

jobs:
  deploy-nightly:

    runs-on: macOS-latest

    steps:
    - uses: actions/checkout@v2
    # publish to a branch in current repo using GITHUB_TOKEN and other default settings
    - uses: oleksiyrudenko/gha-git-credentials@v1
      with:
        token: '${{ secrets.GITHUB_TOKEN }}'
    - name: Use Node.js 12.x
      uses: actions/setup-node@v1
      with:
        node-version: 12.x
    - run: npm i -g yarn
    - run: yarn install --frozen-lockfile
    - run: yarn deploy-nightly
